### ISSUE TITLE
Gdzie bans

### ISSUE THREAD

**Issue by PLOliwier** [xTeJk/betaspeak#1]
w panelu nie ma pliku bans.php :/

**Comment by PLOliwier** [comment]
<? include("panel/strona/viewer.php"); ?> to też

**Comment by PLOliwier** [comment]
panel/strona/viewer.php

**Comment by xTeJk** [comment]
Cześć, dopiero teraz zauważyłem założony temat, wrzuciłem pliki których brakowało, zapoznaj się z readme:
https://github.com/xTeJk/betaspeak/tree/master/panel
